shibuya = [
    "タイガーデン", "モンスーンカフェ", "ガパオ食堂", "ゴールデン・バーニング", "チャオタイ", "コンロー",
    "ソフルフードバンコク", "ティーヌン", "シリパイリン", "タイ料理研究所",

    # 行きたくない
    "アジアの味", "サワディー",

    # やや遠い
    "ガイトーンTokyo",

    # 狭くて定例ランチ向きじゃない
    # "パッポンキッチン",

    # 遠い
    # "ワンディッシュタイ",

    # ランチやってない勢
    # "バグース", "ダオタイ", "ア・カーム",
]
